### ISSUE TITLE
Small contribution ideas?

### ISSUE THREAD

**Issue by ghost** [hammerlab/genomic-reads#9]
I might contribute something small to this project, if you can indicate a few short tasks that might help.

I'm new to bioinformatics and have a lot of terminology left to review. I know Haskell and used to use Scala.

**Comment by ryan-williams** [comment]
Hi @kanishka-azimi! Sorry for the delayed response here.

This repository is a small component within [hammerlab/pageant](https://github.com/hammerlab/pageant); I'm sure there are things that could be interesting for you to work on somewhere in there.

I stalled out developing more of the interesting domain-relevant bits a year or so ago while trying to perfect tooling+processes for developing+maintaining stand-alone components that composed well. A lot of my mental TODO list still consists of that kind of work, e.g. automating releases and corresponding version upgrades downstream, producing docsites, etc.

However, there is definitely room to move things forward at "the application layer", e.g. in [coverage-depth](https://github.com/hammerlab/coverage-depth) or [guacamole](https://github.com/hammerlab/guacamole). Most [guacamole issues](https://github.com/hammerlab/guacamole) still basically stand, I think, and I just noticed that coverage-depth's issues are still [over on the pageant repo](https://github.com/hammerlab/pageant/issues) due to the way I moved/renamed some things at some point ☹️

If you have more specific interests you'd like to push in the direction of, I'd love to hear about it!

**Comment by ghost** [comment]
Thanks. No worries on any delay. I just didn't want leave an abandoned TODO here. Since I'm still getting familiar with basic terminology in bioinformatics, I don't have an explicit direction to push towards. I'm mostly looking to get very brief exposure to some pieces, which will trigger me to understand the terminology specific to a given piece.

I'll browse through what you have linked. 

Regarding perfecting tooling and processes for maintaining lots of components, here are some approaches I have used with scattered Haskell projects at recent organizations:
- mono repo - bring everything together, reduce automation needed for cloning various repos on dev and test machines and tracking inter-package versions. At databrary, I chose two mono-repos - the main repo and a second shadow repo called databrary-incubator. If something really general purpose and reusable emerged that others might want to make large contributions to, I would break that out into its own repo at that point. Of course, there are drawbacks also.
- consider ERB or any template language if you are managing lots of similar build file or package descriptions
- shell scripts and makefiles to document even very simple commands
- i use jenkins on ec2 as my defacto approach, but whatever build system you choose, having one interface showing the status of all test suites helps

**Comment by ryan-williams** [comment]
Thanks for those recommendations!

"Bioinformatics" is very broad… are you interested in genomics specifically? Or is your bias more toward any biofx that uses Scala or other functional-ish languages? 

Either way, [ADAM](https://github.com/bigdatagenomics/adam) (and [bigdatagenomics](http://bdgenomics.org/)) is a good project and community to look at, if you haven't, and may have more in the way of extant starter issues you can poke at.
